import NoCompromise.BV.WeakGradientVariation
import Mathlib.Analysis.SpecialFunctions.SmoothTransition
import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus

/-!
# A measurable majorant for smooth superlevel perimeters

One-sided smooth transitions approximate strict superlevel indicators. The
variation lower-semicontinuity theorem, Tonelli, and Fatou give a measurable
majorant with the gradient-mass bound, without any measurability premise for
perimeter as a function of the level.
-/

noncomputable section

open MeasureTheory Filter Metric Set InnerProductSpace
open scoped NNReal ENNReal Topology Gradient

namespace LiquidDrop

set_option maxSynthPendingDepth 8

/-- The transition derivative is nonnegative. -/
lemma smoothTransition_deriv_nonneg (x : ℝ) : 0 ≤ deriv Real.smoothTransition x :=
  Real.smoothTransition.monotone.deriv_nonneg

/-- The transition derivative is continuous. -/
lemma continuous_deriv_smoothTransition : Continuous (deriv Real.smoothTransition) :=
  (Real.smoothTransition.contDiff (n := 1)).continuous_deriv le_rfl

/-- The transition derivative is supported in the unit interval. -/
lemma tsupport_deriv_smoothTransition_subset :
    tsupport (deriv Real.smoothTransition) ⊆ Icc (0 : ℝ) 1 := by
  apply closure_minimal _ isClosed_Icc
  intro x hx
  by_contra h
  simp only [mem_Icc, not_and_or, not_le] at h
  have hz : deriv Real.smoothTransition x = 0 := by
    rcases h with hx0 | hx1
    · have he : Real.smoothTransition =ᶠ[𝓝 x] fun _ => (0 : ℝ) := by
        filter_upwards [gt_mem_nhds hx0] with y hy
        exact Real.smoothTransition.zero_of_nonpos hy.le
      simpa using he.deriv_eq
    · have he : Real.smoothTransition =ᶠ[𝓝 x] fun _ => (1 : ℝ) := by
        filter_upwards [lt_mem_nhds hx1] with y hy
        exact Real.smoothTransition.one_of_one_le hy.le
      simpa using he.deriv_eq
  exact hx hz

lemma hasCompactSupport_deriv_smoothTransition : HasCompactSupport (deriv Real.smoothTransition) :=
  isCompact_Icc.of_isClosed_subset (isClosed_tsupport _) tsupport_deriv_smoothTransition_subset

/-- The transition derivative is a probability density. -/
lemma integral_deriv_smoothTransition : (∫ x : ℝ, deriv Real.smoothTransition x) = 1 := by
  rw [← setIntegral_eq_integral_of_forall_compl_eq_zero (s := Icc (0 : ℝ) 1)
    (fun x hx => image_eq_zero_of_notMem_tsupport
      (fun hs => hx (tsupport_deriv_smoothTransition_subset hs)))]
  rw [integral_Icc_eq_integral_Ioc,
    ← intervalIntegral.integral_of_le (by norm_num : (0 : ℝ) ≤ 1),
    intervalIntegral.integral_deriv_eq_sub]
  · simp
  · intro x _
    exact (Real.smoothTransition.contDiff (n := 1)).differentiable one_ne_zero x
  · exact continuous_deriv_smoothTransition.intervalIntegrable 0 1

/-- The transition profile used for a strict superlevel set, with scale `j + 1`. -/
def smoothSuperlevel {n : ℕ} (j : ℕ) (t : ℝ)
    (f : EuclideanSpace ℝ (Fin n) → ℝ) (x : EuclideanSpace ℝ (Fin n)) : ℝ :=
  Real.smoothTransition (((j : ℝ) + 1) * (f x - t))

/-- At every scalar value, the one-sided profile converges to the strict superlevel indicator. -/
lemma tendsto_smoothTransition_nat_mul_sub (a t : ℝ) :
    Tendsto (fun j : ℕ => Real.smoothTransition (((j : ℝ) + 1) * (a - t))) atTop
      (𝓝 (if t < a then 1 else 0)) := by
  by_cases hta : t < a
  · simp only [hta, ↓reduceIte]
    apply tendsto_const_nhds.congr'
    obtain ⟨N, hN⟩ := exists_nat_gt (1 / (a - t))
    filter_upwards [eventually_ge_atTop N] with j hj
    apply (Real.smoothTransition.one_of_one_le _).symm
    have hNj : (N : ℝ) ≤ j := Nat.cast_le.mpr hj
    have hmul : 1 < (N : ℝ) * (a - t) := (div_lt_iff₀ (sub_pos.mpr hta)).mp hN
    nlinarith
  · simp only [hta, ↓reduceIte]
    have he : (fun j : ℕ => Real.smoothTransition (((j : ℝ) + 1) * (a - t))) =
        fun _ => (0 : ℝ) := by
      funext j
      apply Real.smoothTransition.zero_of_nonpos
      exact mul_nonpos_of_nonneg_of_nonpos (by positivity) (sub_nonpos.mpr (le_of_not_gt hta))
    rw [he]
    exact tendsto_const_nhds

/-- The level-variable probability kernel generated by the transition derivative. -/
def smoothSuperlevelKernel (k a t : ℝ) : ℝ :=
  k * deriv Real.smoothTransition (k * (a - t))

lemma smoothSuperlevelKernel_nonneg {k : ℝ} (hk : 0 ≤ k) (a t : ℝ) :
    0 ≤ smoothSuperlevelKernel k a t :=
  mul_nonneg hk (smoothTransition_deriv_nonneg _)

/-- The transition kernel has unit mass for every positive scale and every center. -/
lemma lintegral_smoothSuperlevelKernel {k : ℝ} (hk : 0 < k) (a : ℝ) :
    (∫⁻ t : ℝ, ENNReal.ofReal (smoothSuperlevelKernel k a t)) = 1 := by
  have hd : Integrable (deriv Real.smoothTransition) :=
    continuous_deriv_smoothTransition.integrable_of_hasCompactSupport
      hasCompactSupport_deriv_smoothTransition
  have hi : Integrable (smoothSuperlevelKernel k a) :=
    ((hd.comp_mul_left' hk.ne').comp_sub_left a).const_mul k
  rw [← ofReal_integral_eq_lintegral_ofReal hi
    (Eventually.of_forall fun t => smoothSuperlevelKernel_nonneg hk.le a t)]
  change ENNReal.ofReal (∫ t : ℝ, k * deriv Real.smoothTransition (k * (a - t))) = 1
  rw [integral_const_mul, integral_sub_left_eq_self
    (fun t => deriv Real.smoothTransition (k * t)) volume a,
    Measure.integral_comp_mul_left, integral_deriv_smoothTransition]
  simp [abs_of_pos (inv_pos.mpr hk), smul_eq_mul, hk.ne']

/-- Smooth superlevel approximations preserve C¹ regularity on the original open domain. -/
lemma contDiffOn_smoothSuperlevel {n : ℕ} {U : Set (EuclideanSpace ℝ (Fin n))}
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U) (j : ℕ) (t : ℝ) :
    ContDiffOn ℝ 1 (smoothSuperlevel j t f) U :=
  Real.smoothTransition.contDiff.comp_contDiffOn (contDiffOn_const.mul (hf.sub contDiffOn_const))

/-- Exact gradient formula for the one-sided approximation on the open domain. -/
lemma gradient_smoothSuperlevel {n : ℕ} {U : Set (EuclideanSpace ℝ (Fin n))}
    (hU : IsOpen U) {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U)
    (j : ℕ) (t : ℝ) {x : EuclideanSpace ℝ (Fin n)} (hx : x ∈ U) :
    gradient (smoothSuperlevel j t f) x =
      smoothSuperlevelKernel ((j : ℝ) + 1) (f x) t • gradient f x := by
  have hdf := ((hf.contDiffAt (hU.mem_nhds hx)).differentiableAt one_ne_zero).hasFDerivAt
  have hd := ((Real.smoothTransition.contDiff (n := 1)).differentiable one_ne_zero
    (((j : ℝ) + 1) * (f x - t))).hasDerivAt
  have he := (hd.comp_hasFDerivAt x ((hdf.sub_const t).const_mul ((j : ℝ) + 1))).fderiv
  apply PiLp.ext
  intro i
  rw [gradient_apply_eq_fderiv_single]
  change fderiv ℝ (Real.smoothTransition ∘ (fun y => ((j : ℝ) + 1) * (f y - t))) x
    (EuclideanSpace.single i 1) = _
  rw [he]
  simp only [smul_apply, PiLp.smul_apply, smul_eq_mul,
    gradient_apply_eq_fderiv_single, smoothSuperlevelKernel]
  ring

/-- The extended variation of a smooth profile is its kernel-weighted gradient mass. -/
lemma variation_smoothSuperlevel {n : ℕ} {U : Set (EuclideanSpace ℝ (Fin n))}
    (hU : IsOpen U) {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U)
    (j : ℕ) (t : ℝ) :
    variation (smoothSuperlevel j t f) U =
      ∫⁻ x in U, ENNReal.ofReal (smoothSuperlevelKernel ((j : ℝ) + 1) (f x) t) *
        ENNReal.ofReal ‖gradient f x‖ := by
  rw [variation_eq_lintegral_norm_gradient_of_contDiffOn hU (contDiffOn_smoothSuperlevel hf j t)]
  apply lintegral_congr_ae
  filter_upwards [ae_restrict_mem hU.measurableSet] with x hx
  rw [gradient_smoothSuperlevel hU hf j t hx, norm_smul,
    Real.norm_of_nonneg (smoothSuperlevelKernel_nonneg (by positivity) _ _),
    ENNReal.ofReal_mul (smoothSuperlevelKernel_nonneg (by positivity) _ _)]

/-- On every compact subset of the domain, the smooth profiles converge in L¹
 to the strict superlevel indicator localized to the domain. -/
lemma tendsto_integral_abs_smoothSuperlevel_sub_indicator {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U)
    (t : ℝ) {K : Set (EuclideanSpace ℝ (Fin n))} (hK : IsCompact K) (hKU : K ⊆ U) :
    Tendsto (fun j => ∫ x in K, |smoothSuperlevel j t f x -
      (U ∩ f ⁻¹' Ioi t).indicator (fun _ => (1 : ℝ)) x|) atTop (𝓝 0) := by
  let E := U ∩ f ⁻¹' Ioi t
  have hE : IsOpen E := hf.continuousOn.isOpen_inter_preimage hU isOpen_Ioi
  have hiE := (locallyIntegrable_indicator_one
    hE.measurableSet.nullMeasurableSet).integrableOn_isCompact hK
  have hi (j : ℕ) : IntegrableOn (smoothSuperlevel j t f) K :=
    ((contDiffOn_smoothSuperlevel hf j t).continuousOn.locallyIntegrableOn
      hU.measurableSet).integrableOn_compact_subset hKU hK
  have ht : Tendsto (fun j => ∫ x in K, |smoothSuperlevel j t f x -
      E.indicator (fun _ => (1 : ℝ)) x|) atTop (𝓝 (∫ x in K, (0 : ℝ))) := by
    apply tendsto_integral_of_dominated_convergence (fun _ => (1 : ℝ))
    · intro j
      exact ((hi j).sub hiE).abs.aestronglyMeasurable
    · exact integrableOn_const hK.measure_lt_top.ne
    · intro j
      filter_upwards [ae_restrict_mem hK.measurableSet] with x hx
      rw [Real.norm_eq_abs, abs_abs]
      have hs0 := Real.smoothTransition.nonneg (((j : ℝ) + 1) * (f x - t))
      have hs1 := Real.smoothTransition.le_one (((j : ℝ) + 1) * (f x - t))
      change |Real.smoothTransition _ - E.indicator (fun _ => (1 : ℝ)) x| ≤ 1
      by_cases hxE : x ∈ E
      · rw [indicator_of_mem hxE]
        exact abs_le.mpr ⟨by linarith, by linarith⟩
      · rw [indicator_of_notMem hxE, sub_zero, abs_of_nonneg hs0]
        exact hs1
    · filter_upwards [ae_restrict_mem hK.measurableSet] with x hx
      have hvalue : E.indicator (fun _ => (1 : ℝ)) x = if t < f x then 1 else 0 := by
        by_cases ht : t < f x <;> simp [E, hKU hx, ht]
      rw [hvalue]
      have hz := (tendsto_smoothTransition_nat_mul_sub (f x) t).sub_const
        (if t < f x then 1 else 0)
      simpa [smoothSuperlevel] using hz.abs
  simpa using ht

/-- Every strict superlevel perimeter is bounded by the lower limit of smooth-profile energies. -/
lemma perimeterIn_superlevel_le_liminf_smoothSuperlevel {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U) (t : ℝ) :
    perimeterIn {x | t < f x} U ≤
      liminf (fun j => variation (smoothSuperlevel j t f) U) atTop := by
  let E := U ∩ f ⁻¹' Ioi t
  have hE : IsOpen E := hf.continuousOn.isOpen_inter_preimage hU isOpen_Ioi
  have he : {x | t < f x}.indicator (fun _ => (1 : ℝ)) =ᵐ[volume.restrict U]
      E.indicator (fun _ => (1 : ℝ)) := by
    filter_upwards [ae_restrict_mem hU.measurableSet] with x hx
    by_cases ht : t < f x <;> simp [E, hx, ht]
  rw [perimeterIn, variation_congr_ae U he]
  exact variation_le_liminf_of_locally_l1 hU
    (fun j => (contDiffOn_smoothSuperlevel hf j t).continuousOn.locallyIntegrableOn
      hU.measurableSet)
    ((locallyIntegrable_indicator_one hE.measurableSet.nullMeasurableSet).locallyIntegrableOn U)
    (fun K hK hKU => tendsto_integral_abs_smoothSuperlevel_sub_indicator hU hf t hK hKU)

/-- Joint measurability of the transition energy density on the domain subtype. -/
lemma measurable_smoothSuperlevel_density {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U) (k : ℝ) :
    Measurable (fun p : ℝ × U => ENNReal.ofReal (smoothSuperlevelKernel k (f p.2) p.1) *
      ENNReal.ofReal ‖gradient f p.2‖) := by
  have hcf : Continuous (fun p : ℝ × U => f p.2) :=
    hf.continuousOn.domRestrict.comp continuous_snd
  have hcg : Continuous (fun p : ℝ × U => gradient f p.2) :=
    (continuousOn_gradient_of_contDiffOn hU hf).domRestrict.comp continuous_snd
  have hck : Continuous (fun p : ℝ × U => smoothSuperlevelKernel k (f p.2) p.1) :=
    continuous_const.mul (continuous_deriv_smoothTransition.comp
      (continuous_const.mul (hcf.sub continuous_fst)))
  exact hck.measurable.ennreal_ofReal.mul hcg.norm.measurable.ennreal_ofReal

/-- Each profile's variation is a measurable function of its level. -/
lemma measurable_variation_smoothSuperlevel {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U) (j : ℕ) :
    Measurable (fun t => variation (smoothSuperlevel j t f) U) := by
  let μ : Measure U := volume.comap (Subtype.val : U → EuclideanSpace ℝ (Fin n))
  have : SigmaFinite μ := by
    apply SigmaFinite.of_map μ (f := Subtype.val)
      (MeasurableEmbedding.subtype_coe hU.measurableSet).measurable.aemeasurable
    dsimp [μ]
    rw [map_comap_subtype_coe hU.measurableSet]
    infer_instance
  have hm : Measurable (fun t : ℝ =>
      ∫⁻ x : U, ENNReal.ofReal (smoothSuperlevelKernel ((j : ℝ) + 1) (f x) t) *
        ENNReal.ofReal ‖gradient f x‖ ∂μ) :=
    Measurable.lintegral_prod_right
      (measurable_smoothSuperlevel_density hU hf ((j : ℝ) + 1))
  have he (t : ℝ) : variation (smoothSuperlevel j t f) U =
      ∫⁻ x : U, ENNReal.ofReal (smoothSuperlevelKernel ((j : ℝ) + 1) (f x) t) *
        ENNReal.ofReal ‖gradient f x‖ ∂μ := by
    rw [variation_smoothSuperlevel hU hf j t]
    exact (lintegral_subtype_comap hU.measurableSet _).symm
  simpa only [← he] using hm

/-- Integrating any transition profile's variation over all levels gives precisely
 the extended gradient mass. -/
lemma lintegral_variation_smoothSuperlevel {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U) (j : ℕ) :
    (∫⁻ t : ℝ, variation (smoothSuperlevel j t f) U) =
      ∫⁻ x in U, ENNReal.ofReal ‖gradient f x‖ := by
  let μ : Measure U := volume.comap (Subtype.val : U → EuclideanSpace ℝ (Fin n))
  have : SigmaFinite μ := by
    apply SigmaFinite.of_map μ (f := Subtype.val)
      (MeasurableEmbedding.subtype_coe hU.measurableSet).measurable.aemeasurable
    dsimp [μ]
    rw [map_comap_subtype_coe hU.measurableSet]
    infer_instance
  have he (t : ℝ) : variation (smoothSuperlevel j t f) U =
      ∫⁻ x : U, ENNReal.ofReal (smoothSuperlevelKernel ((j : ℝ) + 1) (f x) t) *
        ENNReal.ofReal ‖gradient f x‖ ∂μ := by
    rw [variation_smoothSuperlevel hU hf j t]
    exact (lintegral_subtype_comap hU.measurableSet _).symm
  simp_rw [he]
  rw [lintegral_lintegral_swap (measurable_smoothSuperlevel_density hU hf
    ((j : ℝ) + 1)).aemeasurable]
  calc
    _ = ∫⁻ x : U, ENNReal.ofReal ‖gradient f x‖ ∂μ := by
      apply lintegral_congr
      intro x
      have hmeas : Measurable (fun t : ℝ =>
          ENNReal.ofReal (smoothSuperlevelKernel ((j : ℝ) + 1) (f x) t)) :=
        (continuous_const.mul (continuous_deriv_smoothTransition.comp
          (continuous_const.mul (continuous_const.sub continuous_id)))).measurable.ennreal_ofReal
      rw [lintegral_mul_const _ hmeas,
        lintegral_smoothSuperlevelKernel (by positivity), one_mul]
    _ = _ := lintegral_subtype_comap (μ := volume) hU.measurableSet
      (fun x => ENNReal.ofReal ‖gradient f x‖)

/-- A measurable pointwise majorant of all smooth superlevel perimeters, whose total
 mass is bounded by the full gradient mass; either side may be infinite. -/
theorem exists_measurable_superlevel_perimeter_majorant_of_contDiffOn {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U) :
    ∃ q : ℝ → ℝ≥0∞, Measurable q ∧
      (∀ t, perimeterIn {x | t < f x} U ≤ q t) ∧
      (∫⁻ t : ℝ, q t) ≤ ∫⁻ x in U, ENNReal.ofReal ‖gradient f x‖ := by
  refine ⟨fun t => liminf (fun j => variation (smoothSuperlevel j t f) U) atTop,
    Measurable.liminf (fun j => measurable_variation_smoothSuperlevel hU hf j),
    perimeterIn_superlevel_le_liminf_smoothSuperlevel hU hf, ?_⟩
  calc
    _ ≤ liminf (fun j => ∫⁻ t : ℝ, variation (smoothSuperlevel j t f) U) atTop :=
      lintegral_liminf_le (fun j => measurable_variation_smoothSuperlevel hU hf j)
    _ = _ := by
      simp_rw [lintegral_variation_smoothSuperlevel hU hf]
      exact liminf_const _

/-- The finite-gradient-mass version of the measurable smooth coarea majorant. -/
theorem exists_measurable_superlevel_perimeter_majorant_of_integrable_gradient {n : ℕ}
    {U : Set (EuclideanSpace ℝ (Fin n))} (hU : IsOpen U)
    {f : EuclideanSpace ℝ (Fin n) → ℝ} (hf : ContDiffOn ℝ 1 f U)
    (hgrad : IntegrableOn (gradient f) U) :
    ∃ q : ℝ → ℝ≥0∞, Measurable q ∧
      (∀ t, perimeterIn {x | t < f x} U ≤ q t) ∧
      (∫⁻ t : ℝ, q t) ≤ ENNReal.ofReal (∫ x in U, ‖gradient f x‖) := by
  rw [ofReal_integral_norm_eq_lintegral_enorm hgrad]
  simp only [← ofReal_norm]
  exact exists_measurable_superlevel_perimeter_majorant_of_contDiffOn hU hf

end LiquidDrop
